name: Support Request
description: Report a bug or request help. Please read the HBUP documentation, including the troubleshooting and best practices sections, before creating a support request.
body:
  - type: markdown
    attributes:
      value: |
        ### Before opening a support request, please ensure you have read the [documentation](https://github.com/hjdhjd/homebridge-unifi-protect#documentation), especially the [best practices](https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/BestPractices.md) and [troubleshooting](https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/Troubleshooting.md) pages. Questions and topics already addressed in the documentation, or in prior issue reports, will be closed without a response.

  - type: input
    id: hbupversion
    attributes:
      label: Homebridge UniFi Protect Version
      description: Which version of Homebridge UniFi Protect (HBUP) are you running on?
      placeholder: e.g. v6.16.0
    validations:
      required: true

  - type: input
    id: homebridgeos
    attributes:
      label: Homebridge Platform and OS
      description: What hardware and operating system are you running Homebridge on?
      placeholder: e.g. macOS Sonoma
    validations:
      required: true

  - type: input
    id: homebridge
    attributes:
      label: Homebridge Version
      description: Which version of Homebridge are you running on?
      placeholder: e.g. v1.7.0
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node Version
      description: Which version of Node are you running on?
      placeholder: e.g. v18.1.0
    validations:
      required: true

  - type: input
    id: unifios
    attributes:
      label: UniFi OS Version
      description: Which version of UniFi OS is your Protect controller running on?
      placeholder: e.g. v3.1.16
    validations:
      required: true

  - type: input
    id: protect
    attributes:
      label: UniFi Protect Controller Version
      description: "Which version of the UniFi Protect Controller are you running on? **Note: beta/EA versions are completely unsupported by HBUP, and your request will be closed.**"
      placeholder: e.g. v2.9.33
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the problem
      description: Please describe the issue you're encountering, and ensure you include steps to reproduce, as well as your HBUP JSON configuration and log entries, if appropriate.
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Homebridge HBUP JSON configuration
      description: Please copy and paste your Homebridge HBUP JSON configuration. Ensure that you redact sensitive information like passwords. This will be automatically formatted into code, so no need for backticks.
      placeholder: Paste your HBUP configuration from Homebridge (gear icon in the Homebridge webUI next to HBUP, then select JSON config). Copy and paste it here.
      render: json
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: HBUP log output
      description: Please copy and paste ***the complete Homebridge HBUP startup log output in addition to any specific errors you'd like to highlight. Without this, your support request may be closed without comment***. This will be automatically formatted into code, so no need for backticks.
      placeholder: Please paste the complete HBUP startup logs and any other relevant log entries here. Remember to redact any sensitive information.
      render: shell
    validations:
      required: true

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel
      description: By submitting this issue, you are acknowledging that you are only using the Ubiquiti Official release channels for UniFi Protect and UniFi OS and that you are **not** running early access or beta firmwares (or operating systems) from either Ubiquiti or Apple. **All issues relating to early access or beta firmwares will be closed without comment.** [Read the HBUP documentation for more](https://github.com/hjdhjd/homebridge-unifi-protect#things-to-be-aware-of).
      options:
        - label: I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.
          required: true
